### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by vitulicny** [branflake2267/GWT-Maps-V3-Api#21]
Hello, i try to use your great lib, but i am getting this error so i thought you might help me. when i try to use your autocomplete in the fresh new project it works fine. when i try to integrate in my existing dialog box i get this error:

---

15:19:04.689 [ERROR] [customer] Uncaught exception escaped
com.google.gwt.core.client.JavaScriptException: (TypeError): Cannot read property 'Autocomplete' of undefined
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:248)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:561)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:269)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.maps.client.placeslib.Autocomplete$.createJso(Autocomplete.java)
    at com.google.gwt.maps.client.placeslib.Autocomplete$.newInstance(Autocomplete.java:32)
    at com.sengaro.getataxi.calechelight.client.views.customer.AddressDialog$1.run(AddressDialog.java:61)
    at com.google.gwt.ajaxloader.client.ExceptionHelper.runProtected(ExceptionHelper.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:292)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:546)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:363)
    at java.lang.Thread.run(Thread.java:680)

---

My code:

---

```
final TextBox tb = new TextBox();
    tb.setStyleName("background: #FFFFFF;");

    RootPanel.get().add(tb);
    boolean sensor = false;
    ArrayList<LoadLibrary> loadLibraries = new ArrayList<LoadApi.LoadLibrary>();
    loadLibraries.add(LoadLibrary.PLACES);   
    LoadApi.go(new Runnable() {
      public void run() {
          AutocompleteType[] types = new AutocompleteType[2];
            types[0] = AutocompleteType.ESTABLISHMENT;
            types[1] = AutocompleteType.GEOCODE;

            AutocompleteOptions options = AutocompleteOptions.newInstance();
            options.setTypes(types);

        Element e = tb.getElement();
        Autocomplete o = Autocomplete.newInstance(e, options);

      }
    }, loadLibraries , sensor);
```

---

Do you have any ideas what could be wrong, please? Thank you very much.
Vitek

**Comment by branflake2267** [comment]
Could be I have a spelling error in the binding to javascript. I'll have to take a look and see after work.

**Comment by vitulicny** [comment]
ok thx :)

**Comment by vitulicny** [comment]
any updates, please?

**Comment by twistedpair** [comment]
Vit, I just tried your code sample in the current showcase code and it worked just fine. Are you using the most recent version of the API? Please let me know if you're still experiencing this issue. Thanks.

BTW, from your error, it appears that you don't have any maps API loaded. Can you confirm you're inherited the proper API modules?
