### ISSUE TITLE
Exception on creation of MapWidget

### ISSUE THREAD

**Issue by rajivbarik** [branflake2267/GWT-Maps-V3-Api#65]
Hi,

I am using the GWT-Maps-v3-Api in a GWT application and getting an exception during run time. Please let me know if I am missing-out something. 

Below is the code and the exception.

//Code 

```
public void onModuleLoad() {
    splitLayoutPanel.addWest(leftPanel, 50);
    MapOptions option = MapOptions.newInstance(); // this line throws the exception
    MapWidget map = new MapWidget(option);
    splitLayoutPanel.addWest(map, 100);
}
```

//Exception

com.google.gwt.core.client.JavaScriptException: (TypeError): Cannot read property 'maps' of undefined
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:248)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:561)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:269)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.maps.client.base.LatLng$.createJso(LatLng.java)
    at com.google.gwt.maps.client.base.LatLng$.newInstance(LatLng.java:37)
    at com.google.gwt.maps.client.base.LatLng$.newInstance(LatLng.java:27)
    at com.google.gwt.maps.client.MapOptions$.setDefaults(MapOptions.java:72)
    at com.google.gwt.maps.client.MapOptions$.newInstance(MapOptions.java:44)
    at sharedliving.client.SharedLiving.onModuleLoad(SharedLiving.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:396)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:525)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:363)
    at java.lang.Thread.run(Unknown Source)

**Comment by twistedpair** [comment]
Ravi,

This appears to be being thrown by the following line (javascript):

``` javascript
 return new $wnd.google.maps.LatLng(lat, lng, noWrap);
```

'maps' would be undefined if you had not loaded the Google Maps API. Can you confirm that you've inherited the this library's module and that the Google Maps API js file has loaded in your browser? Thanks.

**Comment by rajivbarik** [comment]
Thanks Joseph. I was missing the reference to Google Maps API js in the html file
